# -*- coding: utf-8 -*-
"""Sales_Forcasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcpLDSDHf96TQwb18cWfp4yzt_61aQC2

# STEP 1 — INSTALL LIBRARIES
"""

!pip install prophet xgboost holidays statsmodels openpyxl

"""# STEP 2 — IMPORT LIBRARIES"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import holidays
import warnings

from sklearn.metrics import mean_absolute_error, mean_squared_error
from xgboost import XGBRegressor

warnings.filterwarnings("ignore")

"""# STEP 3 — LOAD DATASET"""

df = pd.read_csv('/content/Forecasting Case- Study.xlsx - Sheet1.csv')

"""# STEP 4 — CHECK DATA"""

print(df.head())

print(df.columns)

print(df.info())

"""# STEP 5 — RENAME COLUMNS"""

df.rename(columns={
    'Date': 'date',
    'State': 'state',
    'Sales': 'sales'
}, inplace=True)

"""# STEP 6 — CONVERT DATE"""

df['date'] = pd.to_datetime(
    df['date'],
    errors='coerce'
)

"""# STEP 7 — REMOVE BAD DATES"""

df = df.dropna(subset=['date'])

"""# STEP 8 — SORT DATA"""

df = df.sort_values(['state', 'date'])

print(df.columns)

df.head()

"""# STEP 9 — FIX SALES COLUMN"""

df.rename(columns={
    'Date': 'date',
    'State': 'state',
    'Weekly_Sales': 'sales'
}, inplace=True)

"""# STEP 10 — CHECK NULLS"""

print(df.isnull().sum())

df.rename(columns={
    'Total': 'sales'
}, inplace=True)

print(df.columns)

"""# STEP 11 — PLOT SALES TREND"""

plt.figure(figsize=(15,5))

states = df['state'].unique()[:3]

for state in states:

    temp = df[df['state'] == state]

    plt.plot(
        temp['date'],
        temp['sales'],
        label=state
    )

plt.xlabel("Date")

plt.ylabel("Sales")

plt.title("Sales Trend by State")

plt.legend()

plt.show()

"""# STEP 12 — CREATE LAG FEATURES"""

df['lag_1'] = (
    df.groupby('state')['sales']
    .shift(1)
)

df['lag_7'] = (
    df.groupby('state')['sales']
    .shift(7)
)

df['lag_30'] = (
    df.groupby('state')['sales']
    .shift(30)
)

"""# STEP 13 — CREATE ROLLING FEATURES"""

# =========================
# CLEAN SALES COLUMN
# =========================

df['sales'] = (
    df['sales']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.strip()
)

# =========================
# CONVERT SALES TO NUMERIC
# =========================

df['sales'] = pd.to_numeric(
    df['sales'],
    errors='coerce'
)

# =========================
# FILL MISSING SALES VALUES
# =========================

df['sales'] = df['sales'].interpolate()

# =========================
# CREATE LAG FEATURES
# =========================

df['lag_1'] = (
    df.groupby('state')['sales']
    .shift(1)
)

df['lag_7'] = (
    df.groupby('state')['sales']
    .shift(7)
)

df['lag_30'] = (
    df.groupby('state')['sales']
    .shift(30)
)

# =========================
# CREATE ROLLING FEATURES
# =========================

df['rolling_mean_7'] = (
    df.groupby('state')['sales']
    .rolling(7)
    .mean()
    .reset_index(0, drop=True)
)

df['rolling_std_7'] = (
    df.groupby('state')['sales']
    .rolling(7)
    .std()
    .reset_index(0, drop=True)
)

# =========================
# CREATE DATE FEATURES
# =========================

df['day_of_week'] = (
    df['date']
    .dt
    .dayofweek
)

df['month'] = (
    df['date']
    .dt
    .month
)

df['week'] = (
    df['date']
    .dt
    .isocalendar()
    .week
    .astype(int)
)

# =========================
# CREATE HOLIDAY FEATURE
# =========================

india_holidays = holidays.India()

df['is_holiday'] = df['date'].apply(
    lambda x: 1 if x in india_holidays else 0
)

# =========================
# REMOVE NULLS CREATED BY LAGS
# =========================

df = df.dropna(subset=[
    'lag_1',
    'lag_7',
    'lag_30',
    'rolling_mean_7',
    'rolling_std_7'
])

# =========================
# CHECK DATA
# =========================

print(df.head())

print(df.shape)

"""# STEP 14 — TRAIN TEST SPLIT"""

df = df.reset_index(drop=True)

split_index = int(len(df) * 0.8)

train = df.iloc[:split_index]

test = df.iloc[split_index:]

"""# STEP 15 — FEATURES LIST"""

features = [
    'lag_1',
    'lag_7',
    'lag_30',
    'rolling_mean_7',
    'rolling_std_7',
    'day_of_week',
    'month',
    'week',
    'is_holiday'
]

"""# STEP 16 — CREATE X AND y"""

X_train = train[features]

y_train = train['sales']

X_test = test[features]

y_test = test['sales']

"""# STEP 17 — CHECK SHAPES"""

print(X_train.shape)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

"""# STEP 18 — TRAIN XGBOOST"""

model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5
)

model.fit(X_train, y_train)

"""# STEP 19 — PREDICT"""

preds = model.predict(X_test)

"""# STEP 20 — EVALUATE MODEL"""

mae = mean_absolute_error(
    y_test,
    preds
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        preds
    )
)

print("MAE:", mae)

print("RMSE:", rmse)

"""# STEP 21 — PLOT PREDICTIONS"""

plt.figure(figsize=(15,5))

plt.plot(
    y_test.values[:100],
    label='Actual'
)

plt.plot(
    preds[:100],
    label='Predicted'
)

plt.legend()

plt.title("Actual vs Predicted")

plt.show()

"""# STEP 22 — SAVE MODEL"""

import joblib

joblib.dump(
    model,
    'best_model.pkl'
)

"""# STEP 23 — DOWNLOAD MODEL"""

from google.colab import files

files.download('best_model.pkl')